files:
  - source: /bundle/Resources/translations/ezplatform_fields_groups.en.xlf
    translation: >-

  - source: /bundle/Resources/translations/ezrepoforms_content.en.xlf
    translation: >-

  - source: /bundle/Resources/translations/ezrepoforms_content_type.en.xlf
    translation: >-

  - source: /bundle/Resources/translations/ezrepoforms_language.en.xlf
    translation: >-

  - source: /bundle/Resources/translations/ezrepoforms_role.en.xlf
    translation: >-

  - source: /bundle/Resources/translations/ezrepoforms_section.en.xlf
    translation: >-

  - source: /bundle/Resources/translations/ezrepoforms_user_registration.en.xlf
    translation: >-

  - source: /bundle/Resources/translations/messages.en.xlf
    translation: /bundle/Resources/translations/messages.%locale_with_underscore%.xlf
  - source: /bundle/Resources/translations/validators.en.xlf
    translation: /bundle/Resources/translations/validators.%locale_with_underscore%.xlf
