files:
  - source: /bundle/Resources/translations/ezplatform_fields_groups.en.xlf
    translation: /bundle/Resources/translations/ezplatform_fields_groups.%locale%.xlf
  - source: /bundle/Resources/translations/ezrepoforms_content.en.xlf
    translation: /bundle/Resources/translations/ezrepoforms_content.%locale%.xlf
  - source: /bundle/Resources/translations/ezrepoforms_content_type.en.xlf
    translation: /bundle/Resources/translations/ezrepoforms_content_type.%locale%.xlf
  - source: /bundle/Resources/translations/ezrepoforms_language.en.xlf
    translation: /bundle/Resources/translations/ezrepoforms_language.%locale%.xlf
  - source: /bundle/Resources/translations/ezrepoforms_role.en.xlf
    translation: /bundle/Resources/translations/ezrepoforms_role.%locale%.xlf
  - source: /bundle/Resources/translations/ezrepoforms_section.en.xlf
    translation: /bundle/Resources/translations/ezrepoforms_section.%locale%.xlf
  - source: /bundle/Resources/translations/ezrepoforms_user_registration.en.xlf
    translation: /bundle/Resources/translations/ezrepoforms_user_registration.%locale%.xlf
  - source: /bundle/Resources/translations/messages.en.xlf
    translation: /bundle/Resources/translations/messages.%locale%.xlf
  - source: /bundle/Resources/translations/validators.en.xlf
    translation: /bundle/Resources/translations/validators.%locale%.xlf
